// WOODWAVE HOME — Handcrafted willow, rattan & solid wood furniture
// All images are local static assets in /public/img — generated by AI.

export type ColorVariant = {
  name: string;
  hex: string;
};

export type Product = {
  id: string;
  name: string;
  category:
    | "rattan-seating"
    | "wooden-tables"
    | "woven-storage"
    | "rattan-beds"
    | "lighting"
    | "hall-console";
  price: number;
  oldPrice?: number;
  badge?: "new" | "bestseller" | "sale";
  colors: ColorVariant[];
  defaultColor: string;
  image: string;
  rating: number;
  reviews: number;
  inStock: boolean;
  shortDescription: string;
  description: string;
  specs: { label: string; value: string }[];
};

// Local static assets — resolved at runtime by Next.js / static export.
const IMG = (name: string) => `/img/${name}.png`;

export const products: Product[] = [
  {
    id: "willowcrest-armchair",
    name: "WillowCrest Rattan Armchair",
    category: "rattan-seating",
    price: 489,
    oldPrice: 590,
    badge: "bestseller",
    colors: [
      { name: "Natural Rattan", hex: "#d4a373" },
      { name: "Walnut Stain", hex: "#6b4423" },
      { name: "Black Wash", hex: "#2a2a2a" },
      { name: "Whitewash", hex: "#e8d5b7" },
    ],
    defaultColor: "Natural Rattan",
    image: IMG("p_willowcrest_armchair"),
    rating: 4.9,
    reviews: 124,
    inStock: true,
    shortDescription: "Hand-woven rattan armchair on a solid oak frame.",
    description:
      "WillowCrest is woven by hand from sustainable Indonesian rattan over a kiln-dried solid oak frame. The seat uses a seven-step weave pattern passed down through three generations of weavers. A separate duck-down cushion with a washable linen cover is included. Each piece takes a single craftsperson 22 hours to complete.",
    specs: [
      { label: "Frame", value: "Solid oak" },
      { label: "Weave", value: "Indonesian rattan" },
      { label: "Dimensions", value: "78 × 82 × 84 cm" },
      { label: "Cushion", value: "Linen + duck-down" },
    ],
  },
  {
    id: "oakwhisper-dining-chair",
    name: "OakWhisper Dining Chair",
    category: "rattan-seating",
    price: 219,
    badge: "new",
    colors: [
      { name: "Natural Oak", hex: "#c8a273" },
      { name: "Smoked Oak", hex: "#6b4423" },
      { name: "Black Oak", hex: "#1a1a1a" },
    ],
    defaultColor: "Natural Oak",
    image: IMG("p_oakwhisper_chair"),
    rating: 4.7,
    reviews: 68,
    inStock: true,
    shortDescription: "Solid oak chair with hand-caned seat in natural rattan.",
    description:
      "OakWhisper pairs a solid oak frame with a hand-caned seat woven from natural rattan reed. The caning is done using the traditional six-way pattern that flexes with weight yet springs back to shape. Joinery is mortise-and-tenon with wooden pegs — no metal fasteners, no glue on the visible surfaces. Sold individually, ships fully assembled.",
    specs: [
      { label: "Frame", value: "Solid oak" },
      { label: "Seat", value: "Hand-caned rattan" },
      { label: "Dimensions", value: "46 × 52 × 84 cm" },
      { label: "Joinery", value: "Mortise & tenon" },
    ],
  },
  {
    id: "halcyon-lounge-chair",
    name: "Halcyon Lounge Chair",
    category: "rattan-seating",
    price: 549,
    oldPrice: 650,
    badge: "sale",
    colors: [
      { name: "Terra", hex: "#a35233" },
      { name: "Graphite", hex: "#2a2a2a" },
      { name: "Ivory", hex: "#e8d5b7" },
    ],
    defaultColor: "Terra",
    image: IMG("p_halcyon_chair"),
    rating: 4.8,
    reviews: 41,
    inStock: true,
    shortDescription: "Bent-plywood shell on a hand-finished solid beech base.",
    description:
      "Halcyon is built around a steam-bent plywood shell finished in our workshop with three coats of natural oil. The base is solid beech with a 360° swivel bearing. The seat geometry was tuned for the kind of long evenings that call for a glass of wine and a good book. Each chair is signed and numbered by the maker.",
    specs: [
      { label: "Shell", value: "Steam-bent plywood" },
      { label: "Base", value: "Solid beech, swivel" },
      { label: "Dimensions", value: "82 × 86 × 94 cm" },
      { label: "Finish", value: "3 coats natural oil" },
    ],
  },
  {
    id: "monolith-coffee-table",
    name: "Monolith Live-Edge Coffee Table",
    category: "wooden-tables",
    price: 749,
    badge: "bestseller",
    colors: [
      { name: "Natural Oak", hex: "#c8a273" },
      { name: "Walnut", hex: "#5a3a22" },
      { name: "Black", hex: "#1a1a1a" },
    ],
    defaultColor: "Natural Oak",
    image: IMG("p_monolith_table"),
    rating: 4.9,
    reviews: 87,
    inStock: true,
    shortDescription: "Live-edge solid oak slab on a blackened steel frame.",
    description:
      "Monolith is built around a single live-edge slab of European oak, dried for 18 months and hand-finished with our oil-wax blend. The natural edge is preserved and lightly sanded to a velvet touch. The base is a 4 mm blackened steel frame. Each table is one-of-a-kind: no two slabs share the same grain.",
    specs: [
      { label: "Top", value: "Live-edge solid oak" },
      { label: "Base", value: "4 mm blackened steel" },
      { label: "Dimensions", value: "110 × 60 × 34 cm" },
      { label: "Weight", value: "32 kg" },
    ],
  },
  {
    id: "harvest-dining-table",
    name: "Harvest Oak Dining Table",
    category: "wooden-tables",
    price: 1290,
    oldPrice: 1520,
    badge: "sale",
    colors: [
      { name: "Natural Oak", hex: "#c8a273" },
      { name: "Smoked Oak", hex: "#6b4423" },
      { name: "Walnut", hex: "#5a3a22" },
    ],
    defaultColor: "Natural Oak",
    image: IMG("p_harvest_table"),
    rating: 4.8,
    reviews: 53,
    inStock: true,
    shortDescription: "Six-seater oak table with breadboard ends and wood pegs.",
    description:
      "Harvest is a six-seater dining table built from solid European oak with traditional breadboard ends that allow the top to move with the seasons. The top is 38 mm thick, joined to the legs with double-mortise joinery and walnut pegs. Seats six comfortably, eight for a special occasion. Reaches you in three flat-packed pieces, assembles in 15 minutes.",
    specs: [
      { label: "Top", value: "Solid oak 38 mm" },
      { label: "Joinery", value: "Breadboard + walnut pegs" },
      { label: "Dimensions", value: "200 × 100 × 75 cm" },
      { label: "Seats", value: "6–8" },
    ],
  },
  {
    id: "willowdream-bed-frame",
    name: "WillowDream Bed Frame",
    category: "rattan-beds",
    price: 989,
    badge: "new",
    colors: [
      { name: "Natural Oak + Rattan", hex: "#c8a273" },
      { name: "Smoked Oak + Rattan", hex: "#6b4423" },
      { name: "White Oak + Rattan", hex: "#e8d5b7" },
    ],
    defaultColor: "Natural Oak + Rattan",
    image: IMG("p_willowbed"),
    rating: 4.9,
    reviews: 34,
    inStock: true,
    shortDescription: "Oak bed frame with a hand-woven rattan headboard.",
    description:
      "WillowDream combines a solid oak frame with a hand-woven rattan headboard — a modern take on the classic mid-century woven bed. The headboard is woven in our workshop using the seven-step pattern that gives gentle flex against your back. Fits a standard 160 × 200 cm mattress (not included). The frame sits on tapered oak legs and is shipped flat-packed.",
    specs: [
      { label: "Frame", value: "Solid oak" },
      { label: "Headboard", value: "Hand-woven rattan" },
      { label: "Mattress", value: "160 × 200 cm" },
      { label: "Slats", value: "Steam-bent beech" },
    ],
  },
  {
    id: "lumen-walnut-sideboard",
    name: "Lumen Cane-Front Sideboard",
    category: "woven-storage",
    price: 1099,
    oldPrice: 1320,
    badge: "bestseller",
    colors: [
      { name: "Walnut + Cane", hex: "#5a3a22" },
      { name: "Oak + Cane", hex: "#c8a273" },
      { name: "Black + Cane", hex: "#1a1a1a" },
    ],
    defaultColor: "Walnut + Cane",
    image: IMG("p_lumen_sideboard"),
    rating: 4.7,
    reviews: 49,
    inStock: true,
    shortDescription: "Walnut sideboard with hand-caned door panels.",
    description:
      "Lumen blends a solid walnut carcass with hand-caned door panels — the cane softens the visual weight of the sideboard while letting light filter through. Inside, three compartments with adjustable shelves and soft-close doors. Solid brass hardware, hand-rubbed oil finish. A modern heirloom that gets more beautiful with use.",
    specs: [
      { label: "Frame", value: "Solid walnut" },
      { label: "Panels", value: "Hand-caned rattan" },
      { label: "Hardware", value: "Solid brass" },
      { label: "Dimensions", value: "180 × 45 × 72 cm" },
    ],
  },
  {
    id: "studio-open-shelf",
    name: "Studio Open Bookshelf",
    category: "woven-storage",
    price: 689,
    badge: "new",
    colors: [
      { name: "Oak + Cane Back", hex: "#c8a273" },
      { name: "Walnut + Cane Back", hex: "#5a3a22" },
      { name: "Black + Cane Back", hex: "#1a1a1a" },
    ],
    defaultColor: "Oak + Cane Back",
    image: IMG("p_studio_shelf"),
    rating: 4.8,
    reviews: 73,
    inStock: true,
    shortDescription: "Open oak shelving with hand-cane back panels.",
    description:
      "Studio brings the warmth of woven rattan to an open shelving unit. Five solid oak shelves sit on a blackened steel frame, with hand-cane panels stretched across the back. The cane catches light and casts gentle shadow patterns. Each shelf holds up to 25 kg. Ideal for books, plants, ceramics, or a small library of vinyl.",
    specs: [
      { label: "Shelves", value: "Solid oak, 30 mm" },
      { label: "Back", value: "Hand-cane panels" },
      { label: "Frame", value: "Blackened steel" },
      { label: "Load", value: "25 kg / shelf" },
    ],
  },
  {
    id: "halo-rattan-pendant",
    name: "Halo Hand-Woven Pendant",
    category: "lighting",
    price: 249,
    badge: "bestseller",
    colors: [
      { name: "Natural Rattan", hex: "#d4a373" },
      { name: "Smoked Rattan", hex: "#6b4423" },
      { name: "Black Rattan", hex: "#1a1a1a" },
    ],
    defaultColor: "Natural Rattan",
    image: IMG("p_halo_pendant"),
    rating: 4.9,
    reviews: 96,
    inStock: true,
    shortDescription: "Hand-woven rattan pendant, 45 cm diameter.",
    description:
      "Halo is woven by hand from natural Indonesian rattan around a hand-bent steel ring. The weave pattern throws soft, organic shadows across the walls and ceiling when lit. Each pendant comes with a 1 m chain and a ceiling rose. Compatible with E27 LED bulbs up to 15 W. Allow 2–3 weeks for weaving when out of stock.",
    specs: [
      { label: "Material", value: "Hand-woven rattan" },
      { label: "Diameter", value: "45 cm" },
      { label: "Chain", value: "100 cm, adjustable" },
      { label: "Fitting", value: "E27, max 15 W" },
    ],
  },
  {
    id: "arc-floor-lamp",
    name: "Arc Brass Floor Lamp",
    category: "lighting",
    price: 379,
    oldPrice: 450,
    badge: "sale",
    colors: [
      { name: "Aged Brass", hex: "#b08d57" },
      { name: "Blackened Brass", hex: "#1a1a1a" },
      { name: "Polished Brass", hex: "#d4a373" },
    ],
    defaultColor: "Aged Brass",
    image: IMG("p_arc_lamp"),
    rating: 4.8,
    reviews: 67,
    inStock: true,
    shortDescription: "Solid brass arc lamp on a hand-turned oak base.",
    description:
      "Arc is a 1960s-inspired arc lamp reimagined for today. The arc is hand-bent solid brass, weighted at the bottom with a hand-turned solid oak disc. The shade is woven natural rattan that softens the LED light into a warm glow. The integrated 12 W LED is dimmable in three colour temperatures, from candle-warm to reading-bright.",
    specs: [
      { label: "Arc", value: "Solid brass" },
      { label: "Base", value: "Solid oak, 8 kg" },
      { label: "Shade", value: "Woven rattan" },
      { label: "Light", value: "12 W LED, dimmable" },
    ],
  },
  {
    id: "aloft-cane-console",
    name: "Aloft Cane Console",
    category: "hall-console",
    price: 489,
    badge: "new",
    colors: [
      { name: "Oak + Cane", hex: "#c8a273" },
      { name: "Walnut + Cane", hex: "#5a3a22" },
      { name: "Black + Cane", hex: "#1a1a1a" },
    ],
    defaultColor: "Oak + Cane",
    image: IMG("p_aloft_console"),
    rating: 4.6,
    reviews: 28,
    inStock: true,
    shortDescription: "Slim hallway console with hand-cane front panels.",
    description:
      "Aloft is a slim hallway console built from solid oak with hand-cane panels on the front. Two drawers with brass pulls hold keys, mail, and small things. The cane front lets the piece breathe — it never feels heavy in a narrow hall. Ships fully assembled in protective crate; we deliver to your room of choice.",
    specs: [
      { label: "Frame", value: "Solid oak" },
      { label: "Fronts", value: "Hand-cane panels" },
      { label: "Drawers", value: "2, soft-close" },
      { label: "Dimensions", value: "110 × 28 × 82 cm" },
    ],
  },
  {
    id: "willowvanity-mirror",
    name: "WillowVanity Mirror Console",
    category: "hall-console",
    price: 399,
    colors: [
      { name: "Oak + Rattan Frame", hex: "#c8a273" },
      { name: "Walnut + Rattan Frame", hex: "#5a3a22" },
    ],
    defaultColor: "Oak + Rattan Frame",
    image: IMG("p_willowvanity"),
    rating: 4.5,
    reviews: 19,
    inStock: false,
    shortDescription: "Console + bevelled mirror framed in hand-woven rattan.",
    description:
      "WillowVanity pairs a slim oak console with a bevelled mirror framed in hand-woven rattan. The weave wraps the entire frame in a seven-step pattern, softening the geometry of the glass. A small shelf below the mirror holds keys, a bowl, a phone on charge. The console is wall-mounted with two solid-brass cleats.",
    specs: [
      { label: "Frame", value: "Solid oak + rattan" },
      { label: "Mirror", value: "4 cm bevel" },
      { label: "Dimensions", value: "80 × 22 × 180 cm" },
      { label: "Mounting", value: "Brass cleats included" },
    ],
  },
];

export type Category = {
  id: string;
  name: string;
  description: string;
  image: string;
  count: number;
};

export const categories: Category[] = [
  {
    id: "rattan-seating",
    name: "Rattan Seating",
    description: "Hand-woven armchairs, dining chairs, lounges",
    image: IMG("cat_rattan_seating"),
    count: 18,
  },
  {
    id: "wooden-tables",
    name: "Solid Wood Tables",
    description: "Live-edge, dining, and coffee tables",
    image: IMG("cat_wooden_tables"),
    count: 14,
  },
  {
    id: "woven-storage",
    name: "Cane & Rattan Storage",
    description: "Sideboards, shelves, cabinets with woven panels",
    image: IMG("cat_woven_storage"),
    count: 11,
  },
  {
    id: "rattan-beds",
    name: "Rattan Beds",
    description: "Oak frames with woven headboards",
    image: IMG("cat_rattan_beds"),
    count: 6,
  },
  {
    id: "lighting",
    name: "Woven Lighting",
    description: "Hand-woven pendants and brass+rattan lamps",
    image: IMG("cat_lighting"),
    count: 9,
  },
  {
    id: "hall-console",
    name: "Hall & Console",
    description: "Slim consoles, mirrors, vanity pieces",
    image: IMG("cat_hall_console"),
    count: 8,
  },
];

export const heroBackground = IMG("hero");

export const aboutImage = IMG("about");

export const galleryImages = [
  IMG("gallery1"),
  IMG("gallery2"),
  IMG("gallery3"),
  IMG("gallery4"),
  IMG("gallery5"),
  IMG("gallery6"),
  IMG("gallery7"),
  IMG("gallery8"),
];

export const testimonials = [
  {
    name: "Anna K.",
    city: "Dublin",
    initial: "A",
    rating: 5,
    text:
      "I ordered the WillowCrest armchair for a reading corner and it arrived fully assembled in a wooden crate. The weave is flawless and the cushion is the kind you sink into. It's the most beautiful piece in our home now.",
  },
  {
    name: "Michael R.",
    city: "Carlow",
    initial: "M",
    rating: 5,
    text:
      "The Harvest oak table is the first piece of furniture I've bought that I expect to outlive me. The breadboard ends, the pegs, the smell of the oil-wax finish — it's the kind of work you can't fake. Delivery was on the day promised.",
  },
  {
    name: "Sarah O.",
    city: "Dublin 15",
    initial: "S",
    rating: 5,
    text:
      "Lumen is the cane-front sideboard I'd been hunting for for two years. Real cane, real walnut, real brass. The shadows the cane throws in the afternoon sun are unreal. Thank you for making honest things.",
  },
];

// Contact info — sourced from the original woodwave.ie
export const contactInfo = {
  phone: "+353 85 7614192",
  phoneHref: "tel:+353857614192",
  email: "mcos2666@gmail.com",
  emailHref: "mailto:mcos2666@gmail.com",
  address: "R14RY62 Athy, co. Kildare, Ireland",
  hours: "Monday – Sunday 9:00 AM – 7:00 PM",
  hoursShort: "Mon – Sun 9–19",
};
